###
http://localhost:3000/tasks

###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
  "title": "Task3",
  "description": "Desc3"
}

###
DELETE http://localhost:3000/tasks/79b724a7-15cb-4b7f-943e-6e2368bb6b39

###
GET http://localhost:3000/tasks/79b724a7-15cb-4b7f-943e-6e2368bb6b39

###
PATCH http://localhost:3000/tasks/79b724a7-15cb-4b7f-943e-6e2368bb6b39/status
content-type: application/json

{
  "status": "DONE"
}

###
http://localhost:3000/tasks?status=IN_PROGRESS
