###
http://localhost:3000/tasks

###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
  "title": "Task2",
  "description": "Desc323213"
}

###
DELETE http://localhost:3000/tasks/2

###
GET http://localhost:3000/tasks/1

###
PATCH http://localhost:3000/tasks/1/status
content-type: application/json

{
  "status": "DONE"
}

###
http://localhost:3000/tasks?status=DONE

###
http://localhost:3000/tasks?term=Desc3
